import { NextRequest, NextResponse } from "next/server";
import { jsonWithFallback } from "@/lib/ai/json-with-fallback";
import type {
  DependencyMapReport,
  DependencyNode,
  PrerequisiteGap,
  SourceRef,
} from "@/types";

function isDependencyMapReport(v: unknown): v is DependencyMapReport {
  const r = v as any;
  return !!r && typeof r === "object" && (typeof r.root === "string" || Array.isArray(r.nodes));
}

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SYSTEM = `You are ExamIntel's prerequisite-dependency mapper — an expert at building a knowledge graph of topics → subtopics → concepts with prerequisite edges for competitive-exam preparation.

Your job:
1. Parse the user's input (an exam name, subject, topic, syllabus text, or a custom curriculum) and break it down into a DAG of learning nodes.
2. For every node, record: stable id ("n1", "n2", "n3", ... assigned in topological order, roots first), topic, optional subtopic, optional concept, optional difficulty, the ids of its prerequisite nodes (prerequisites), the ids of nodes that depend on it (dependents), exam relevance, and a level (depth: 0 for roots, +1 per prerequisite hop).
3. Detect prerequisite gaps — concepts the learner MUST master before attempting the root, that are commonly under-prepared. For each gap: missing prerequisite, why it matters (1-2 sentences), a recommended numbered learning sequence, practice recommendations (specific actionable items), and an estimated effort (e.g. "~10 hours").
4. Provide a flat recommended learning sequence (a flat list of node topic names ordered from foundational → advanced).
5. Assign mastery ONLY as "Not Started" for every node by default. NEVER pretend the user has mastered, practiced, or is learning anything without explicit evidence. The default state must be "Not Started" for all nodes.
6. Tag every source as type "AI_ANALYSIS" since this is generated by AI reasoning (label: "AI Dependency Analysis").

Hard rules:
- ids MUST be "n1", "n2", ... never reuse ids, never reference non-existent ids in prerequisites/dependents.
- prerequisites and dependents arrays MUST be perfectly symmetric: if node A lists B in prerequisites, then B MUST list A in dependents.
- level must equal the longest path from any root (a root is a node with empty prerequisites). Roots have level 0.
- Aim for 6–15 nodes for a topic, 12–25 for a subject, 20–40 for a full syllabus/exam. Keep it focused and useful, not exhaustive.
- Return STRICT JSON ONLY that exactly matches DependencyMapReport. No markdown, no commentary, no code fences.

DependencyMapReport = {
  root: string,                              // the original subject/topic/exam being mapped
  nodes: DependencyNode[],                   // ordered topologically (roots first)
  gaps: PrerequisiteGap[],                   // detected missing foundations
  recommendedLearningSequence: string[],     // flat ordered topic names
  sources: SourceRef[],                      // all tagged AI_ANALYSIS
  generatedAt: string                       // ISO timestamp
}

DependencyNode = {
  id: string,                               // "n1", "n2", ...
  topic: string,
  subtopic?: string,
  concept?: string,
  difficulty?: string,                       // "Easy" | "Medium" | "Hard"
  prerequisites: string[],                  // ids of nodes that must be learned first
  dependents: string[],                      // ids of nodes that need THIS node first
  examRelevance?: string,                   // "High" | "Medium" | "Low"
  mastery: "Not Started" | "Introduced" | "Learning" | "Practicing" | "Weak" | "Improving" | "Strong" | "Mastered",  // ALWAYS "Not Started" unless evidence exists
  level: number                             // depth in graph
}

PrerequisiteGap = {
  missingPrerequisite: string,
  whyItMatters: string,
  recommendedSequence: string[],            // ordered learning steps for this gap
  practiceRecommendations: string[],        // concrete practice items
  estimatedEffort?: string                  // e.g. "~12 hours"
}`;

const SCHEMA = `Strict JSON. Top-level object: { root, nodes[], gaps[], recommendedLearningSequence[], sources[], generatedAt }.
- nodes[].id must be "n1","n2",... in topological order (roots first).
- Symmetric prerequisites/dependents. level = longest path from any root.
- All mastery = "Not Started". All sources[].type = "AI_ANALYSIS".`;

export async function POST(req: NextRequest) {
  try {
    const body = await req.json().catch(() => ({}));
    const input = typeof body?.input === "string" ? body.input.trim() : "";
    const inputType: string =
      body?.inputType && ["exam", "subject", "topic", "syllabus", "custom"].includes(body.inputType)
        ? body.inputType
        : "topic";

    if (!input) {
      return NextResponse.json(
        { error: "Missing required field 'input'." },
        { status: 400 }
      );
    }

    const user = `Build a prerequisite dependency map for the following input.

Input: """${input}"""
Input type: ${inputType}

Return STRICT JSON matching the DependencyMapReport schema. Use stable ids n1, n2, ... in topological order. Every node mastery = "Not Started". All sources tagged AI_ANALYSIS. generatedAt = ISO timestamp.`;

    const report = await jsonWithFallback<DependencyMapReport>(SYSTEM, user, SCHEMA, isDependencyMapReport);

    // Defensive clean-up: normalize fields the AI might have gotten wrong.
    let cleaned: DependencyMapReport;
    try {
      cleaned = sanitizeReport(report, input);
    } catch (normErr) {
      console.error("[dependency/map] sanitizeReport error:", normErr);
      cleaned = report;
    }

    return NextResponse.json({ report: cleaned });
  } catch (e: any) {
    return NextResponse.json(
      { error: e?.message ?? "Dependency map generation failed" },
      { status: 500 }
    );
  }
}

// ------------------------------------------------------------------
// sanitizeReport — defensive cleanup so the UI never crashes on AI drift
// ------------------------------------------------------------------
function sanitizeReport(raw: DependencyMapReport, fallbackRoot: string): DependencyMapReport {
  const nodesRaw = Array.isArray(raw?.nodes) ? raw.nodes : [];

  // 1. Build a stable id map: accept "n1" style; otherwise rewrite ids.
  const idMap = new Map<string, string>();
  let counter = 0;
  const nodes: DependencyNode[] = nodesRaw.map((n) => {
    const stableId = `n${++counter}`;
    if (n?.id) idMap.set(String(n.id), stableId);
    return {
      id: stableId,
      topic: String(n?.topic ?? "Untitled topic").slice(0, 200),
      subtopic: n?.subtopic ? String(n.subtopic).slice(0, 200) : undefined,
      concept: n?.concept ? String(n.concept).slice(0, 200) : undefined,
      difficulty: n?.difficulty ? String(n.difficulty).slice(0, 50) : undefined,
      prerequisites: Array.isArray(n?.prerequisites)
        ? n.prerequisites.map((p) => String(p)).filter(Boolean)
        : [],
      dependents: Array.isArray(n?.dependents)
        ? n.dependents.map((d) => String(d)).filter(Boolean)
        : [],
      examRelevance: n?.examRelevance ? String(n.examRelevance).slice(0, 50) : undefined,
      mastery: normalizeMastery(n?.mastery),
      level: Number.isFinite(n?.level) ? Math.max(0, Math.floor(n.level as number)) : 0,
    };
  });

  // 2. Re-map any "n1"-style ids the AI used to OUR ids; drop invalid refs.
  nodes.forEach((n) => {
    n.prerequisites = n.prerequisites
      .map((p) => idMap.get(p) ?? p)
      .filter((p) => nodes.some((x) => x.id === p) && p !== n.id);
    n.dependents = n.dependents
      .map((d) => idMap.get(d) ?? d)
      .filter((d) => nodes.some((x) => x.id === d) && d !== n.id);
  });

  // 3. Enforce symmetry: if A has B in prerequisites, B must have A in dependents.
  nodes.forEach((n) => {
    n.prerequisites.forEach((pid) => {
      const dep = nodes.find((x) => x.id === pid);
      if (dep && !dep.dependents.includes(n.id)) dep.dependents.push(n.id);
    });
    n.dependents.forEach((did) => {
      const pre = nodes.find((x) => x.id === did);
      if (pre && !pre.prerequisites.includes(n.id)) pre.prerequisites.push(n.id);
    });
  });

  // 4. Recompute level = longest path from any root (BFS over prerequisites).
  const levelOf = (id: string, cache = new Map<string, number>()): number => {
    if (cache.has(id)) return cache.get(id)!;
    const n = nodes.find((x) => x.id === id)!;
    if (!n.prerequisites.length) {
      cache.set(id, 0);
      return 0;
    }
    let max = 0;
    for (const p of n.prerequisites) {
      // guard against cycles
      cache.set(id, 0);
      const lv = levelOf(p, cache);
      cache.set(id, Math.max(max, lv + 1));
      max = Math.max(max, lv + 1);
    }
    cache.set(id, max);
    return max;
  };
  nodes.forEach((n) => (n.level = levelOf(n.id)));

  // 5. Sort topologically (roots first, then by level, then id).
  nodes.sort((a, b) => a.level - b.level || a.id.localeCompare(b.id, undefined, { numeric: true }));

  // 6. Gaps.
  const gaps: PrerequisiteGap[] = Array.isArray(raw?.gaps)
    ? raw.gaps.map((g) => ({
        missingPrerequisite: String(g?.missingPrerequisite ?? "").slice(0, 200),
        whyItMatters: String(g?.whyItMatters ?? "").slice(0, 600),
        recommendedSequence: Array.isArray(g?.recommendedSequence)
          ? g.recommendedSequence.map((s) => String(s)).filter(Boolean)
          : [],
        practiceRecommendations: Array.isArray(g?.practiceRecommendations)
          ? g.practiceRecommendations.map((s) => String(s)).filter(Boolean)
          : [],
        estimatedEffort: g?.estimatedEffort ? String(g.estimatedEffort).slice(0, 80) : undefined,
      })).filter((g) => g.missingPrerequisite)
    : [];

  // 7. Learning sequence.
  const seq: string[] = Array.isArray(raw?.recommendedLearningSequence)
    ? raw.recommendedLearningSequence.map((s) => String(s)).filter(Boolean)
    : nodes.map((n) => n.topic);

  // 8. Sources — force AI_ANALYSIS.
  const sources: SourceRef[] = (Array.isArray(raw?.sources) ? raw.sources : []).map((s) => ({
    type: "AI_ANALYSIS",
    label: String(s?.label ?? "AI Dependency Analysis").slice(0, 100),
    detail: s?.detail ? String(s.detail).slice(0, 200) : undefined,
  }));
  if (!sources.length) sources.push({ type: "AI_ANALYSIS", label: "AI Dependency Analysis" });

  const root = String(raw?.root ?? fallbackRoot).slice(0, 200) || fallbackRoot;

  return {
    root,
    nodes,
    gaps,
    recommendedLearningSequence: seq,
    sources,
    generatedAt: raw?.generatedAt && typeof raw.generatedAt === "string"
      ? raw.generatedAt
      : new Date().toISOString(),
  };
}

function normalizeMastery(v: unknown): DependencyNode["mastery"] {
  const s = String(v ?? "Not Started").trim().toLowerCase();
  const allowed: DependencyNode["mastery"][] = [
    "Not Started",
    "Introduced",
    "Learning",
    "Practicing",
    "Weak",
    "Improving",
    "Strong",
    "Mastered",
  ];
  const found = allowed.find((a) => a.toLowerCase() === s);
  return found ?? "Not Started";
}
